// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrmmkdebqgpzdmdbyuej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybW1rZGVicWdwemRtZGJ5dWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NjYxMzUsImV4cCI6MjA4NzM0MjEzNX0.nk90nttXuH3xRvvWQnsOJY8jhbl4rxGVLzYfxEzTktA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});